theme: minima

title: "ABOPSC frontend"

description: "Data Structures 2"

gitorg: "https://github.com/dontran15/frontend-abopsc"

google_analytics:

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-octicons
  - jekyll-toc
  - jekyll-twitter-plugin
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
