remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme
title: "ABOPSC frontend"
description: "Data Structures 2"
gitorg: "https://github.com/dontran15/frontend-abopsc"
url: http://127.0.0.1:4000
baseurl:

